language: node_js
node_js:
    - "10"

install:
    - npm i -g vuepress

script:
    - npm run docs:build
    - git commit -a -m "build docs (travis)"
    - git subtree push --quiet --prefix docs/ origin master >/dev/null 2>&1

cache:
    directories:
        - "node_modules"
