language: node_js
node_js:
    - "10"

install:
    - npm i -g vuepress

script:
    - npm run docs:build

cache:
    directories:
        - "node_modules"
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs
    github-token: $GITHUB_TOKEN
    repo: jkatagi/jkatagi.github.io
    keep-history: true
    target-branch: master
    on:
        branch: master
